inteb/clients/urls.py
from django.contrib import admin
from django.urls import path

from clients.views import clients, add_client, client_detail, add_client_staff, client_staff_detail, client_staff_edit

app_name = 'clients'


urlpatterns = [
    path('', clients,  name='clients'),
    path('add/', add_client, name='add_client'),
    path('client_detail/<int:pk>/', client_detail, name='client_detail'),
    path('add_client_staff/<int:pk>/', add_client_staff, name='add_client_staff'),
    path('client_staff_detail/<int:pk>/', client_staff_detail, name='client_staff_detail'),
    path('client_staff_edit/<int:pk>/', client_staff_edit, name='client_staff_edit'),

]

inteb/inteb/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from .views import index, custom404, tasks

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/', index, name='index'),
    path('', include('staff.urls', namespace='staff')),
    path('tasks/', include('tasks.urls', namespace='tasks')),

]

handler404 = custom404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inteb/tasks/urls.py
from django.contrib import admin
from django.urls import path

from .views import tasks, ticket, add_ticket

app_name = 'tasks'

urlpatterns = [
    path('', tasks, name='tasks'),
    path('ticket/<int:pk>/', ticket, name='ticketdetail'),
    path('add/', add_ticket, name='addticket'),

]

inteb/inteb/views.py
from django.http import HttpResponseNotFound
from django.shortcuts import render


def index(request):
    title = 'ИнТеБ - Главная'

    context = {
        "title": title,
        'user': request.user,
    }
    return render(request, 'inteb/index.html', context=context)



def custom404(request, exception):
    return render(request, 'inteb/err.html')

inteb/inteb/templates/inteb/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static '/css/style.css' %}">

</head>
<body>
   <nav class="navbar navbar-expand-lg ">
  <div class="container">
    {% if user.is_authenticated %}
      <a class="navbar-brand" href="#">{{user.first_name}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      {% endif %}


   <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a href="{% url 'tasks:tasks' %}" class="nav-link active" aria-current="page" href="#">Задачи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'clients:clients' %}">Клиенты</a>
        </li>

      </ul>
  </div>
</nav>
{% block content %}
{% endblock %}



</body>

</html>

inteb/inteb/templates/inteb/err.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
  <link type="text/css" href="{% static '/css/404.css' %}" rel="stylesheet">

</head>
<body>
<div class="travolta">404</div>
</body>
</html>

inteb/inteb/templates/inteb/index.html
{% extends 'inteb/base.html' %}
{% load static %}


{% block content %}

{% endblock %}