inteb/clients/urls.py
from django.contrib import admin
from django.urls import path

from clients.views import clients, add_client, client_detail, add_client_staff, client_staff_detail, client_staff_edit

app_name = 'clients'


urlpatterns = [
    path('', clients,  name='clients'),
    path('add/', add_client, name='add_client'),
    path('client_detail/<int:pk>/', client_detail, name='client_detail'),
    path('add_client_staff/<int:pk>/', add_client_staff, name='add_client_staff'),
    path('client_staff_detail/<int:pk>/', client_staff_detail, name='client_staff_detail'),
    path('client_staff_edit/<int:pk>/', client_staff_edit, name='client_staff_edit'),

]

inteb/inteb/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from .views import index, custom404, tasks

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/', index, name='index'),
    path('', include('staff.urls', namespace='staff')),
    path('tasks/', include('tasks.urls', namespace='tasks')),

]

handler404 = custom404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inteb/clients/models.py
from django.db import models
from staff.models import IntebUser


class Clients(models.Model):
    company_name = models.CharField(verbose_name='Название', max_length=128, )
    office_phone = models.BigIntegerField(verbose_name='Рабочий телефон', blank=True, null=True)
    office_email = models.EmailField(verbose_name='office_email', blank=True, null=True)
    company_address = models.CharField(verbose_name='Адрес', max_length=64, blank=True, null=True)
    external_ip_v4 = models.CharField(verbose_name='внешний ip', max_length=16, default='0.0.0.0')
    is_active = models.BooleanField(verbose_name='активный', default=True)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='создан', auto_now=True)

    def __str__(self):
        return self.company_name


class ClientsStaff(models.Model):
    company = models.ForeignKey(Clients, verbose_name='Компания', related_name='company', on_delete=models.CASCADE)
    lastname = models.CharField(verbose_name='Фамилия', max_length=32)
    firstname = models.CharField(verbose_name='Имя', max_length=32)
    middlename = models.CharField(verbose_name='Отчество', max_length=32, blank=True)
    bdate = models.DateField(verbose_name='День рождения', blank=True, null=True)
    position = models.CharField(verbose_name='Должность', max_length=32, blank=True, null=True)
    work_phone = models.BigIntegerField(verbose_name='рабочий телефон', blank=True, null=True)
    extension_number = models.PositiveIntegerField(verbose_name='(доб.)', blank=True, null=True)
    mobile_phone = models.BigIntegerField(verbose_name='мобильный телефон', blank=True, null=True)
    email = models.EmailField(verbose_name='email', blank=True, null=True)
    comment = models.TextField(verbose_name='Комментарий', blank=True, null=True)
    is_active = models.BooleanField(verbose_name='работает', default=True)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='создан', auto_now=True)


def image_folder(self, filename):
    filename = self.company_img.company_name + '.' + filename.split('.')[1]
    folder = self.company_img.company_name.replace(' ', '_').replace('"', '').replace("'", "")
    return "{0}/{1}".format(folder, filename)


class Images(models.Model):
    img = models.ImageField(verbose_name='изображение', upload_to=image_folder, blank=True)
    company_img = models.ForeignKey(Clients, related_name='client_images', on_delete=models.CASCADE)


class CompanyComments(models.Model):
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    author = models.ForeignKey(IntebUser, related_name='author', on_delete=models.PROTECT)
    company = models.ForeignKey(Clients, related_name='comment', on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

inteb/clients/forms.py
import datetime

from django import forms
from django.forms import DateField, DateInput

from inteb import settings
from .models import Clients, Images, ClientsStaff, CompanyComments


class AddClientForm(forms.ModelForm):
    class Meta:
        model = Clients
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AddClientForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-label', 'form-control', 'col-30'


class ImgToForm(forms.ModelForm):
    class Meta:
        model = Images
        fields = ['img']


class AddClientStaff(forms.ModelForm):
    bdate = DateField(label='День рождения', input_formats=settings.DATE_FORMAT, widget=DateInput(attrs={'type': 'date'}))
    class Meta:
        model = ClientsStaff
        fields = ['lastname', 'firstname', 'middlename', 'bdate', 'position', 'work_phone', 'extension_number', 'mobile_phone', 
                  'email']

    def __init__(self, *args, **kwargs):
        super(AddClientStaff, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-label', 'form-control', 'col-30'


class CompanyCommentForm(forms.ModelForm):
    class Meta:
        model = CompanyComments
        fields = ['comment']

    def __init__(self, *args, **kwargs):
        super(CompanyCommentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-label', 'form-control', 'col-30', 'rows="3"'


class ClientStaffForm(forms.ModelForm):
    bdate = DateField(label='День рождения', input_formats=settings.DATE_FORMAT, widget=DateInput(attrs={'type': 'date'}))

    class Meta:
        model = ClientsStaff
        fields = '__all__'
    # def __init__(self, *args,**kwargs):
    #     super(ClientStaffForm, self).__init__(*args, **kwargs)
    #     for field_name, field in self.fields.items():
    #         field.widget.attrs['class'] = 'form-label', 'form-control', 'col-30', 'rows="3"'

inteb/clients/views.py
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from clients.forms import AddClientForm, ImgToForm, AddClientStaff, CompanyCommentForm, ClientStaffForm
from clients.models import Clients, ClientsStaff, Images
from django.core.cache import cache


# Create your views here.

def clients(request):
    title = 'ИнТеБ - Клиенты'
    all_clients = Clients.objects.all()

    context = {
        'title': title,
        'all_clients': all_clients,

    }

    return render(request, 'clients/clients.html', context)


def add_client(request):
    title = f'ИнТеБ - создание карточки клента'
    clients_form = AddClientForm

    if request.method == 'POST':
        clients_form = AddClientForm(request.POST, request.FILES)
        if clients_form.is_valid():
            clients_form.save()
            return HttpResponseRedirect(reverse('clients:clients'))

    context = {
        'title': title,
        'form': clients_form,
        'user': request.user,
    }

    return render(request, 'clients/add_client.html', context=context)


def client_detail(request, pk):
    client = get_object_or_404(Clients, pk=pk)
    title = f'ИнТеБ - Карточка клиента {client.company_name}'

    if request.method == 'POST':
        clients_form = AddClientForm(request.POST, request.FILES, instance=client)
        img = ImgToForm(request.POST, request.FILES)
        comment = CompanyCommentForm(request.POST, request.FILES)

        if clients_form.is_valid() and img.is_valid() and comment.is_valid():
            img_form = img.save(commit=False)
            comment_form = comment.save(commit=False)
            if comment_form.comment is not '':
                img_form.company_img = Clients.objects.get(id=pk)
                comment_form.company = Clients.objects.get(id=pk)
                comment_form.author = request.user
                clients_form.save()
                img_form.save()
                comment_form.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                img_form.company_img = Clients.objects.get(id=pk)
                clients_form.save()
                img_form.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        clients_form = AddClientForm(instance=client)
        img = ImgToForm()
        comment = CompanyCommentForm()

    context = {
        'title': title,
        'update_form': clients_form,
        'client': client,
        'img': img,
        'comment': comment,

    }

    return render(request, 'clients/client_detail.html', context=context)


def add_client_staff(request, pk):
    client = Clients.objects.get(pk=pk)
    title = f'ИнТеБ - Добавление клиентского сотрудника'

    if request.method == 'POST':
        client_staff_form = AddClientStaff(request.POST, request.FILES)
        if client_staff_form.is_valid():
            staff_form = client_staff_form.save(commit=False)
            staff_form.company = client
            staff_form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    else:
        client_staff_form = AddClientStaff()
        print(request.POST)

    context = {
        'title': title,
        'form': client_staff_form,
        'client': client,

    }

    return render(request, 'clients/add_client_staff.html', context=context)


def client_staff_detail(request, pk):
    client = Clients.objects.get(pk=pk)
    staff = ClientsStaff.objects.all()
    title = f'ИнТеБ - Сотрудники клиента {client.company_name}'

    context = {
        'title': title,
        'client': client,
        'staff': staff,

    }

    return render(request, 'clients/client_staff_detail.html', context=context)


def client_staff_edit(request, pk):
    client_staff = ClientsStaff.objects.get(pk=pk)
    title = f'ИнТеБ - Карточка сотрудника {client_staff.lastname} {client_staff.firstname} {client_staff.middlename}'
    print('1')
    if request.method == 'POST':
        print('пока тут')
        clients_staff_form = ClientStaffForm(request.POST, request.FILES, instance=client_staff)
        if clients_staff_form.is_valid():
            print('ура')
            clients_staff_form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            print(clients_staff_form)
    else:
        clients_staff_form = ClientStaffForm(instance=client_staff)
    # print(request.POST)

    context = {
        'title': title,
        'client_staff': client_staff,
        'edit_form': clients_staff_form,
    }

    return render(request, 'clients/client_staff_edit.html', context=context)

inteb/clients/templates/clients/add_client.html
{% extends 'inteb/base.html' %}
{% load static %}

{% block content %}


<form action="{% url 'clients:add_client' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

    {{ form.as_p }}


<button type="submit" class="btn btn-success">Добавить</button>


</form>


{% endblock %}

inteb/clients/templates/clients/add_client_staff.html
{% extends 'inteb/base.html' %}
{% load static %}

{% block content %}

{{ client.company_name }}

<form action="{% url 'clients:add_client_staff' client.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

    <table>{{ form.as_table }}</table>


<button type="submit" class="btn btn-success">Добавить</button>


</form>


{% endblock %}

inteb/clients/templates/clients/client_detail.html
{% extends 'inteb/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <a href="{% url 'clients:client_staff_detail' client.pk %}" class='btn btn-primary'>Сорудники</a>
    <a href="{% url 'clients:add_client_staff' client.pk %}" class='btn btn-primary'>Добавить сотрудника</a>

        <form action="{% url 'clients:client_detail' client.pk %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

      <div class="row">
          <div class="col block_inside">
              <p class="text-muted">Создан: {{client.created|date:"d-m-Y H:i:s "}} / Обновлен: {{ client.updated|date:"d-m-Y H:i:s" }}</p>
              <div class="row">
                  <table>{{ update_form.as_table }}</table>


              </div>
                                <p class="button"><button type="submit" class="btn btn-success">Сохранить</button></p>

              <div class="row block_inside">
                  <table>
            <thead>
                <tr>
                    <th scope="col">Комментарий</th>
                    <th scope="col">Автор</th>
                </tr>
            </thead>
            <tbody>
              {% for comm in client.comment.all %}
                <tr>
                    <td class="form-control">{{ comm }}</td>
                    <td>({{ comm.author.first_name }} {{ comm.author.last_name }})</td>
                </tr>              {% endfor %}

            </tbody>
            </table>
                  <div class="block_inside">{{ comment }}</div>
                            <p class="button"><button type="submit" class="btn btn-success">Сохранить</button></p>

              </div>
          </div>
          <div class="col">
          <div class="row"> <div class="col block1">
            <div>{{ img }}
            <button type="submit" class="btn btn-success">Сохранить</button>
            <h1>Изображения</h1>

            {% for image in client.client_images.all %}
                     {% if image.img %}
                        {% load thumbnail %}
                {% thumbnail image.img "150" as im %}
                <a href="{{ image.img.url }}">
                     <img src="{{ im.url }}" class="img-thumbnail" alt="">
                </a>
                {% endthumbnail %}

        {% endif %}
    {% endfor %}
               </div>

 </div>
          </div>



      </div>

</div>


{% endblock %}

inteb/clients/templates/clients/client_staff_delete.html
{% extends 'inteb/base.html' %}
{% load static %}

{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ product_to_delete.name }}

    ?
    <form action="{% url 'admin_staff:product_delete' product_to_delete.pk %}" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_staff:products' product_to_delete.category.pk %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

inteb/clients/templates/clients/client_staff_detail.html
{% extends 'inteb/base.html' %}
{% load static %}

{% block content %}

{{ client }}

<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Фамилия</th>
      <th scope="col">Имя</th>
      <th scope="col">Отчество</th>
      <th scope="col">Должность</th>

    </tr>
  </thead>
  <tbody>
  {% for client_staff in staff %}
      {% if client.id == client_staff.company_id %}
      {% if client_staff.is_active %}
    <tr>
      <th scope="row"><a href="{% url 'clients:client_staff_edit' client_staff.pk%}">{{ client_staff.id}}</a></th>
      <td><a href="{% url 'clients:client_staff_edit' client_staff.pk%}">{{ client_staff.lastname}}</a></td>
      <td><a href="{% url 'clients:client_staff_edit' client_staff.pk%}">{{ client_staff.firstname}}</a></td>
      <td><a href="{% url 'clients:client_staff_edit' client_staff.pk%}">{{ client_staff.middlename}}</a></td>
      <td><a href="{% url 'clients:client_staff_edit' client_staff.pk%}">{{ client_staff.position}}</a></td>


    </tr>
     {% else %}
  <tr>
      <th class="text-decoration-line-through" scope="row"><a href="{% url 'clients:client_staff_edit' client_staff.pk%}">{{ client_staff.id}}</a></th>
      <td class="text-decoration-line-through"><a href="{% url 'clients:client_staff_edit' client_staff.pk%}">{{ client_staff.lastname}}</a></td>
      <td class="text-decoration-line-through"><a href="{% url 'clients:client_staff_edit' client_staff.pk%}">{{ client_staff.firstname}}</a></td>
      <td class="text-decoration-line-through"><a href="{% url 'clients:client_staff_edit' client_staff.pk%}">{{ client_staff.middlename}}</a></td>
      <td class="text-decoration-line-through"><a href="{% url 'clients:client_staff_edit' client_staff.pk%}">{{ client_staff.position}}</a></td>


    </tr> {% endif %}

  {% endif %}
{% endfor %}

  </tbody>


{% endblock %}

inteb/clients/templates/clients/client_staff_edit.html
{% extends 'inteb/base.html' %}
{% load static %}

{% block content %}

<div class="block1">
<form action="{% url 'clients:client_staff_edit' client_staff.pk %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <table>
    {{ edit_form.as_table }}
    </table>
    <p class="text-muted">Создан: {{client_staff.created|date:"d-m-Y H:i:s "}} / Обновлен: {{ client_staff.updated|date:"d-m-Y H:i:s" }}</p>
    <p><button type="submit" class="btn btn-success">Сохранить</button></p>

</form>
</div>
{% endblock %}

inteb/clients/templates/clients/clients.html
{% extends 'inteb/base.html' %}
{% load static %}

{% block content %}
<div class="container">
<a href="{% url 'clients:add_client' %}" class="btn btn-success" role="button">Добавить компанию</a>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Наименование</th>
      <th scope="col">Телефон</th>
      <th scope="col">Адрес</th>
      <th scope="col">email</th>


   </tr>
  </thead>
  <tbody>

   <tbody>
              {% for client in all_clients %}
            {% if client.is_active == False %}
    <tr>
        <td class="text-decoration-line-through"><a href="{% url 'clients:client_detail' client.pk%}">{{ client.id }}</a></td>
        <td class="text-decoration-line-through"><a href="{% url 'clients:client_detail' client.pk%}">{{ client.company_name }}</a></td>
        <td class="text-decoration-line-through"><a href="{% url 'clients:client_detail' client.pk%}">{{ client.office_phone }}</a></td>
        <td class="text-decoration-line-through"><a href="{% url 'clients:client_detail' client.pk%}">{{ client.office_email }}</a></td>
        <td class="text-decoration-line-through"><a href="{% url 'clients:client_detail' client.pk%}">{{ client.company_address }}</a></td>

    </tr>
              {% else %}
    <tr>
        <td><a href="{% url 'clients:client_detail' client.pk%}">{{ client.id }}</a></td>
        <td><a href="{% url 'clients:client_detail' client.pk%}">{{ client.company_name }}</a></td>
        <td><a href="{% url 'clients:client_detail' client.pk%}">{{ client.office_phone }}</a></td>
        <td><a href="{% url 'clients:client_detail' client.pk%}">{{ client.office_email }}</a></td>
        <td><a href="{% url 'clients:client_detail' client.pk%}">{{ client.company_address }}</a></td>

    </tr>  {% endif %}
          {% endfor %}
  </tbody>
</table>
</div>
    {% endblock %}