inteb/inteb/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from .views import index, custom404, tasks

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/', index, name='index'),
    path('', include('staff.urls', namespace='staff')),
    path('tasks/', include('tasks.urls', namespace='tasks')),

]

handler404 = custom404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inteb/staff/urls.py
from django.contrib import admin
from django.urls import path

from .views import IntebUserLoginView, IntebUserRegisterView

app_name = 'staff'

urlpatterns = [
    path('', IntebUserLoginView.as_view(redirect_authenticated_user=True),  name='login'),
    path('register/', IntebUserRegisterView.as_view(), name='register')
]

inteb/staff/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.


class IntebUser(AbstractUser):
    birthday = models.DateField(verbose_name='день рождения', default='1900-01-01')
    avatar = models.ImageField(verbose_name='картинка', upload_to='media/avatars', blank=True)
    middle_name = models.CharField(verbose_name='отчество', max_length=150, blank=True)
    create = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    update = models.DateTimeField(verbose_name='обновлен', auto_now_add=True)

inteb/staff/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import SelectDateWidget

from .models import IntebUser
from extras import *


class IntebUserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-control'}))
    middle_name = forms.CharField(label='Отчество', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget= forms.TextInput(attrs={'class': 'form-control'}))
    birthday = forms.DateField(label='Дата рождения', widget=SelectDateWidget(
        years=range(datetime.date.today().year - 15, 1920, -1),
        attrs={'class': 'form-control', })
    )
    avatar = forms.ImageField

    class Meta:
        model = IntebUser
        fields = ['username', 'password1', 'password2','last_name', 'first_name', 'middle_name', 'email', 'birthday',
                  'avatar']


class IntebUserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-control form-outline form-label mb-4'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-control form-outline form-label mb-4'}))

inteb/staff/views.py
from django.contrib import auth
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView

from .forms import IntebUserLoginForm, IntebUserRegisterForm


class IntebUserRegisterView(CreateView):
    form_class = IntebUserRegisterForm
    template_name = 'staff/register.html'

    def get_success_url(self):
        return reverse_lazy('staff:login')

class IntebUserLoginView(LoginView):
    template_name = 'staff/login.html'
    form_class = IntebUserLoginForm

    def get_success_url(self):
        return reverse_lazy('index')

inteb/staff/templates/staff/login.html
{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" >

</head>
<body>
<section class=" text-center text-lg-start">
  <style>
    .rounded-t-5 {
      border-top-left-radius: 0.5rem;
      border-top-right-radius: 0.5rem;
    }

    @media (min-width: 992px) {
      .rounded-tr-lg-0 {
        border-top-right-radius: 0;
      }

      .rounded-bl-lg-5 {
        border-bottom-left-radius: 0.5rem;
      }
    }
  </style>
  <div class="card mb-3">
    <div class="row g-0 d-flex align-items-center">
      <div class="col-lg-4 d-none d-lg-flex">
        <img src="{% static '/img/logo.jpg' %}" alt="Trendy Pants and Shoes"
          class="w-100 rounded-t-5 rounded-tr-lg-0 rounded-bl-lg-5" />
      </div>
      <div class="col-lg-8">
        <div class="card-body py-5 px-md-5 w-25">

          <form method="post">
            {% csrf_token %}
             {{ form.as_p }}

            <div class="row mb-4">
              <div class="col d-flex justify-content-center">
                <!-- Checkbox -->
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
                  <label class="form-check-label" for="form2Example31"> Запомнить </label>
                </div>
              </div>

              <div class="col">
                <!-- Simple link -->
                <a href="#!">Забыли пароль?</a>
              </div>
            </div>

            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block mb-4">Вход</button>
            <p><a href="{% url 'staff:register' %}">Регистрация</a></p>
          </form>

        </div>
      </div>
    </div>
  </div>
</section>

</body>
</html>
<!-- Section: Design Block -->

inteb/staff/templates/staff/register.html
{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" >

</head>
<body>
<section class=" text-center text-lg-start">
  <style>
    .rounded-t-5 {
      border-top-left-radius: 0.5rem;
      border-top-right-radius: 0.5rem;
    }

    @media (min-width: 992px) {
      .rounded-tr-lg-0 {
        border-top-right-radius: 0;
      }

      .rounded-bl-lg-5 {
        border-bottom-left-radius: 0.5rem;
      }
    }
  </style>
  <div class="card mb-3">
    <div class="row g-0 d-flex align-items-center">
      <div class="col-lg-4 d-none d-lg-flex">
        <img src="{% static '/img/logo.jpg' %}" alt="Trendy Pants and Shoes"
          class="w-100 rounded-t-5 rounded-tr-lg-0 rounded-bl-lg-5" />
      </div>
      <div class="col-lg-8">
        <div class="card-body py-5 px-md-5 w-50">

          <form method="post">
            {% csrf_token %}
             {{ form.as_p }}


            <button type="submit" class="btn btn-primary btn-block mb-4">Регистрация</button>

          </form>

        </div>
      </div>
    </div>
  </div>
</section>

</body>
</html>
<!-- Section: Design Block -->