inteb/inteb/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from .views import index, custom404, tasks

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/', index, name='index'),
    path('', include('staff.urls', namespace='staff')),
    path('tasks/', include('tasks.urls', namespace='tasks')),

]

handler404 = custom404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inteb/tasks/urls.py
from django.contrib import admin
from django.urls import path

from .views import tasks, ticket, add_ticket

app_name = 'tasks'

urlpatterns = [
    path('', tasks, name='tasks'),
    path('ticket/<int:pk>/', ticket, name='ticketdetail'),
    path('add/', add_ticket, name='addticket'),

]

inteb/tasks/models.py
from django.db import models
from staff.models import IntebUser

class IntebTasks(models.Model):
    # NEW = 'NEW'
    # IN_WORK = 'IN_WORK'
    # PAUSE = 'PAUSE'
    # COMPLETE = 'COMPLETE'
    # FAIL = 'FAIL'
    #
    # STATUS_CHOICES = (
    #     (NEW, 'Новая'),
    #     (IN_WORK, 'В работе'),
    #     (PAUSE, 'Пауза'),
    #     (COMPLETE, 'Завершено'),
    #     (FAIL, 'Невозможно выполнить'),
    # )

    author = models.ForeignKey(IntebUser, related_name='task_author', null=False, db_index=True, on_delete=models.PROTECT)
    topic = models.CharField(verbose_name='тема', max_length=64, )
    text = models.TextField(verbose_name='текст')
    # is_active = models.BooleanField(default=True)
    # create = models.DateTimeField(verbose_name='дата создания', auto_now_add=True, blank=True)
    # update = models.DateTimeField(verbose_name='дата редактирования', auto_now_add=True, blank=True)
    # deadline = models.DateTimeField(verbose_name='дедлайн', blank=True)
    # status = models.CharField(verbose_name='статус', max_length=30, choices=STATUS_CHOICES)



class Executors(models.Model):
    task = models.ForeignKey(IntebTasks, related_name='task_executor', on_delete=models.CASCADE)
    executor = models.ForeignKey(IntebUser, related_name='user_executor', null=False, on_delete=models.PROTECT)
    create = models.DateTimeField(verbose_name='дата создания', auto_now_add=True, blank=True)
    update = models.DateTimeField(verbose_name='дата редактирования', auto_now_add=True, blank=True)

# class TaskComment(models.Model):
#     task = models.OneToOneField(IntebTasks, related_name='task_comment', on_delete=models.CASCADE)
#     author = models.OneToOneField(IntebUser, related_name='comment_author', null=False,
#                                           on_delete=models.PROTECT)
#     comment_text = models.TextField(verbose_name='текст коммента')
#     create = models.DateTimeField(verbose_name='дата создания', auto_now_add=True, blank=True)
#     update = models.DateTimeField(verbose_name='дата редактирования', auto_now_add=True, blank=True)
#
#
# class TaskPictures(models.Model):
#     task = models.OneToOneField(IntebTasks, related_name='task_picture', blank=True, on_delete=models.CASCADE)
#     author = models.OneToOneField(IntebUser, related_name='picture_author', null=False,
#                                           on_delete=models.PROTECT)
#     picture = models.ImageField(blank=True)
#     create = models.DateTimeField(verbose_name='дата создания', auto_now_add=True, blank=True)
#     update = models.DateTimeField(verbose_name='дата редактирования', auto_now_add=True, blank=True)

inteb/tasks/forms.py
import datetime

from django import forms
from django.forms import SelectDateWidget, DateTimeInput
from django.forms.utils import ErrorList

from .models import IntebUser, IntebTasks, Executors
from extras import *


class AddTicketForm(forms.ModelForm):
    class Meta:
        model = IntebTasks
        fields = ['topic', 'text', ]


    widgets = {
        'topic': forms.TextInput(attrs={'class': 'form-input'}),
        'text': forms.Textarea(attrs={'cols': 30, 'rows': 1, }),
        # 'deadline': DateTimeInput(attrs={'type': "datetime-local"}),
    }

inteb/tasks/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .forms import AddTicketForm
from .models import IntebTasks, Executors


def tasks(request):
    title = 'ИнТеБ - задачи'
    task = IntebTasks.objects.all()
    executor = Executors.objects.all()

    context = {
        'title': title,
        'task': task,
        'executor': executor,
    }

    return render(request, 'tasks/tasks.html', context=context)


def ticket(request, pk):
    title = f'ИнТеБ - задача #{pk}'
    # task = IntebTasks.objects.get(pk=pk)
    # executors = Executors.objects.get(pk=pk)

    context = {
        'title': title,
        'ticket': get_object_or_404(IntebTasks, pk=pk),

    }

    return render(request, 'tasks/ticket.html', context=context)


def add_ticket(request):
    title = f'ИнТеБ - создать задачу'
    task = IntebTasks.objects.all()
    executors = Executors.objects.all()
    ticket_form = AddTicketForm


    if request.method == 'POST':
        ticket_form = AddTicketForm(request.POST, request.FILES)
        print(type(ticket_form))
        if ticket_form.is_valid():
            ticket_form.save()
            return HttpResponseRedirect(reverse('tasks:tasks'))

        else:
            print('invalo\id')

    context = {
        'title': title,
        'ticket': task,
        'executors': executors,
        'form': ticket_form,
        'user': request.user,
    }

    return render(request, 'tasks/add_ticket.html', context=context)

inteb/tasks/templates/tasks/add_ticket.html
{% extends 'inteb/base.html' %}
{% load static %}



{% block content %}

<form action="{% url 'tasks:addticket' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3 w-25">
        <label for="exampleFormControlInput1" class="form-label">Тема</label>
        <input id="exampleFormControlInput1" class="form-control" type="text" value="{{ ticket.topic }}" >
    </div>

    <div class="mb-3 w-25">
        <label for="exampleFormControlTextarea4" class="form-label">Описание</label>
        <textarea class="form-control" id="exampleFormControlTextarea4" rows="5"  type="datetime-local" value="{{ ticket.text }}" ></textarea>
    </div>
    {{ form  }}
    <button type="submit" class="btn btn-success">Добавить</button>


</form>
{% endblock %}

inteb/tasks/templates/tasks/tasks.html
{% extends 'inteb/base.html' %}

{% block content %}
<a class="btn btn-success" href="{% url 'tasks:addticket' %}" role="button">Создать задачу</a>


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Тикет</th>
      <th scope="col">Автор</th>
      <th scope="col">Исполнитель</th>
      <th scope="col">Статус</th>


   </tr>
  </thead>
  <tbody>
          {% for t in task %}
    <tr>
      <th scope="row"><a href="{% url 'tasks:ticketdetail' t.id %}">{{ t.id }}</a></th>
      <td><a href="{% url 'tasks:ticketdetail' t.id %}">{{ t.topic }}</a></td>
      <td>{{ t.author.first_name }} {{ t.author.last_name }}</td>
      <td>
        {% for e in executor %}
            {% if e.task_id == t.id %}
            {{ e.executor.first_name }} {{ e.executor.last_name }}
            {% endif %}
        {% endfor %}
      </td>
        <td>{{ t.status }}</td>
    </tr>
          {% endfor %}
  </tbody>
</table>

{% endblock %}

inteb/tasks/templates/tasks/ticket.html
{% extends 'inteb/base.html' %}
{% load static %}

{% block content %}

<div class="mb-3 w-25">
  <label for="exampleFormControlInput1" class="form-label">Тема</label>
  <input id="exampleFormControlInput1" class="form-control" type="text" value="{{ ticket.topic }}" disabled readonly>
</div>
<div class="mb-3 w-25">
  <label for="exampleFormControlInput1" class="form-label">Автор</label>
  <input id="exampleFormControlInput2" class="form-control" type="text" value="{{ ticket.author }}" disabled readonly>
</div>
<div class="mb-3 w-50">
  <label for="exampleFormControlTextarea1" class="form-label">Описание</label>
  <input id="exampleFormControlTextarea1" class="form-control " type="text" value="{{ ticket.text }}" disabled readonly>
</div>
<div class="mb-3 w-50">
  {{ ticket.create }}
</div>

{{ ticket.get_status_display  }}

{% endblock %}